### PR TITLE
wall L/S, 2x2 crafter, 2 items

### PR DESCRIPTION
**Pull request by stacktrace-error**
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAaaaaaaaaaaAAAAAAAAAAAAAAAAAAAAAAaaaaaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAaaaaaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAaaaaaaaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAaaaaaaaaaaaaaaaaaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAaa

### CODE REVIEW

**Comment by gorodmi** [comment]
image
thats like 6 empty item sprites (:skull:)
resize it ig

**Comment by stacktrace-error** [comment]
I did not know how

**Comment by stacktrace-error** [comment]
better?

**Comment by gorodmi** [comment]
yea, still 1 empty tho

**Comment by gorodmi** [comment]
make it 13x2 iguess

**Pull request merged**
